services:
  wakapi:
    image: ghcr.io/muety/wakapi:latest
    init: true
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    environment:
      # See README.md and config.default.yml for all config options
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_USER: "wakapi"
      WAKAPI_DB_HOST: "db"
      WAKAPI_DB_PORT: "5432"
      WAKAPI_DB_PASSWORD: "${WAKAPI_DB_PASSWORD:-changeme}"
      WAKAPI_PASSWORD_SALT: "${WAKAPI_PASSWORD_SALT:-changeme}"
      WAKAPI_MAIL_SMTP_PASS: "${WAKAPI_MAIL_SMTP_PASS:-}"
    volumes:
      - wakapi-data:/data
    networks:
      - wakapi
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: "wakapi"
      POSTGRES_PASSWORD: "${WAKAPI_DB_PASSWORD:-changeme}"
      POSTGRES_DB: "wakapi"
    volumes:
      - wakapi-db-data:/var/lib/postgresql/data
    networks:
      - wakapi
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  wakapi-data: {}
  wakapi-db-data: {}

networks:
  wakapi: {}